apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: andyduss@gmail.com
    privateKeySecretRef:
      name: my-certificate
    solvers:
    - selector: {}
      http01:
        ingress:
          class: istio
